# Generated by Django 4.2.4 on 2024-03-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiel',
            old_name='materiel_number',
            new_name='type_dordinateur',
        ),
    ]
