# Generated by Django 4.2.4 on 2024-03-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_rename_materiel_number_materiel_type_dordinateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiel',
            old_name='field_of_study',
            new_name='Adresse_IP',
        ),
        migrations.RenameField(
            model_name='materiel',
            old_name='first_name',
            new_name='Modele',
        ),
        migrations.RenameField(
            model_name='materiel',
            old_name='last_name',
            new_name='Processeur',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='gpa',
        ),
        migrations.AddField(
            model_name='materiel',
            name='Mémoire_RAM',
            field=models.CharField(default='8GB', max_length=100),
        ),
        migrations.AddField(
            model_name='materiel',
            name='Taille_du_Disque_Dur',
            field=models.CharField(default='500GB', max_length=100),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='type_dordinateur',
            field=models.CharField(max_length=50),
        ),
    ]
