# Generated by Django 4.2.4 on 2024-03-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0003_rename_field_of_study_materiel_adresse_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='type_dordinateur',
        ),
        migrations.AddField(
            model_name='materiel',
            name='type_d_ordinateur',
            field=models.CharField(default='', max_length=100),
        ),
    ]
