# Generated by Django 4.2.4 on 2024-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0004_remove_materiel_type_dordinateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='References',
            field=models.CharField(default='', max_length=255),
        ),
    ]
