# Generated by Django 4.2.4 on 2024-04-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0006_alter_materiel_type_d_ordinateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='type_d_ordinateur',
            field=models.CharField(choices=[('broken', 'Broken'), ('diagnostic', 'Diagnostic'), ('good_condition', 'Good Condition')], default='good_condition', max_length=100),
        ),
    ]
