# Generated by Django 5.0.3 on 2024-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0007_alter_materiel_type_d_ordinateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='References',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
